name: pytorch
channels:
  - pytorch
  - dglteam/label/cu118
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.10.1
  - scikit-learn=1.5.0
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - tqdm=4.66.4
  - pyyaml=6.0.1
  - requests=2.32.3
  - jupyter
  - notebook=7.2.2
  - ipykernel=6.28.0
  - ipywidgets=8.1.2
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - dgl=1.1.2.cu118
  - tensorflow=2.10.0
  - tensorboard=2.10.0
  - tensorboardx=2.6.2.2
  - h5py=3.11.0
  - pillow=10.3.0
  - openpyxl=3.1.5
  - gensim=4.3.2
  - networkx=2.8.8
  - pip:
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - et-xmlfile==2.0.0
      - filelock==3.14.0
      - fsspec==2024.6.0
      - joblib==1.4.2
      - markupsafe==2.1.5
      - node2vec==0.4.6
      - smart-open==7.0.4
      - sympy==1.12.1
      - threadpoolctl==3.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.3
      - wrapt==1.16.0
